### ISSUE TITLE
背景色问题

### ISSUE THREAD

**Issue by LCC456** [xyxc0673/calendar-remark#12]
1、当标签从“休”改为“班”时，背景色还是红色，如图中17日所示；
2、取消勾选“显示非本月日期”时，还会显示下个月的日期。
![image](https://github.com/xyxc0673/calendar-remark/assets/32818020/f45a1721-de28-4bda-854d-785f35caf589)

**Comment by xyxc0673** [comment]
感谢反馈，第一个是节假日背景色的判断逻辑有点问题，第二个是计算月份天数存在问题
